site_name: Stage Project
site_url: https://Okcase.github.io/ProjetStage/
nav:
    - Home: index.md
    - Countries : 
        - Flandre : flandre.md
        - Luxembourg : luxembourg.md
    - About: about.md
theme : flatly
